name: FirstFrojectDart
description: Đây là ứng dụng biên dịch từ Dart

environment:
  sdk: "^3.2.0"
dependencies:
  build_runner: ^2.4.7 # (cần lấy bản mới tại) https://pub.dev/packages/build_runner#-installing-tab-
  build_test: ^2.2.2 # https://pub.dev/packages/build_test#-installing-tab-
  build_web_compilers: ^4.0.7 # https://pub.dev/packages/build_web_compilers#-installing-tab-

